//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR01.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class employee
    {
        public int id { get; set; }
        [Required(ErrorMessage = "Nombre Requerido")]
        public string nombre { get; set; }
        public string direccion { get; set; }
        [Required(ErrorMessage = "Telefono Requerido")]
        public string telefono { get; set; }
        [Required(ErrorMessage = "Departamento Requerido")]
        public int department_id { get; set; }
    
        public virtual department department { get; set; }
    }
}
